### PR TITLE
Migrate to aws-sdk-go-v2

### PR DESCRIPTION
**Pull request by brandonstrohmeyer**
Migrating to aws-sdk-go-v2 to enable support for STS Regional Endpoints.

Multi-region services such as S3 Multi Region Access Point require the STS token used to interact with the service be issued from a regional STS endpoint. Credentials issued from the current default global endpoint will fail.

- https://docs.aws.amazon.com/sdkref/latest/guide/feature-sts-regionalized-endpoints.html
- https://docs.aws.amazon.com/AmazonS3/latest/userguide/MultiRegionAccessPointRestrictions.html

Summary of changes:
- Migrate to aws-sdk-go-v2.
- Add `global.aws-region` field to config file.
- Add per app `aws-region` config option.
- `DurationSeconds` changed from Int64 to Int32 to satisfy `AssumeRoleWithSAMLInput`.
-  Update README.

### CODE REVIEW

**Comment by bitte-ein-bit** [comment]
Hi @brandonstrohmeyer, 

Thank you for your contribution! Really appreciated. 

Would you mind allowing me to push to your branch so I can merge the  support for a per App endpoint setting in one go?

**Comment by brandonstrohmeyer** [comment]
Thanks for merging this @bitte-ein-bit , any thought on when it will make it into a release?

**Comment by bitte-ein-bit** [comment]
@brandonstrohmeyer I have a release prepared. There is an internal blocker, though, that I'm currently working on. The signing part of the release pipeline is blocked due to this. I would prefer not to release unsigned MacOS binaries. If I can't unblock it until the end of the week, I'll do an unsigned release and another one to follow up once the issue is resolved.

**Comment by bitte-ein-bit** [comment]
@brandonstrohmeyer I released an unsigned pre-release. I could not unblock the signing process until now.

**Pull request merged**
